### PR TITLE
Record and print the mangled C++ symbol

### PR DESCRIPTION
**Pull request by argp**
Good to have.

### CODE REVIEW

**Comment by sferrini** [comment]
Nice idea! Only one thing, isn't it be better to enable it with a flag? (Just to keep the output consistent)

**Comment by Siguza** [comment]
Yaay, someone is actually using my tool.

Anyway, I agree that printing mangled C++ symbols would be a useful feature, but I have a couple of issues with this pull request as it stands:

- I agree with Simone that this feature should be put behind a command line flag.
- If the mangled symbol is emitted to the symbol map at all, ever, the parsing code will have to account for this, while retaining backwards compatibility.
- Your proposed change seems to only print symbols extracted from the original binary, which is going to be wholly incomplete except for those 12.0b1 kernels. Maybe I don't understand your use-case here, but IMO if anything had _real_ value, it'd be the re-generation of stripped symbols, no?

**Comment by Siguza** [comment]
I just pushed v1.6.0 with full support for generating mangled C++ symbols from symbol maps (pass the `-z` flag).  
@argp could you check if that satisfies your needs, and close this pull request if so?

**Comment by argp** [comment]
Yes, it does:

`0x4c8 func=0xfffffff008099584 overrides=0xfffffff008099584 pac=0x5b2b __ZN9IOService18setIdleTimerPeriodEm`

Cheers.

**Pull request closed without merging**
